SELECT 
	P.PAGE_TITLE,
	(CASE WHEN COUNT(PP.PAGE_PLUGIN_NAME) > 0 THEN
		CONCAT(
			'{',
			STRING_AGG(CONCAT(PP.PAGE_PLUGIN_NAME,' : ', PP.PAGE_PLUGIN_DATA), ','),
			'}'
		)
	ELSE '{}' END) AS "DATA"
FROM Lab_31.PAGE P
	LEFT JOIN Lab_31.PAGE_CONTENT PC ON P.PAGE_ID = PC.PAGE_ID
	LEFT JOIN Lab_31.PAGE_PLUGIN PP ON PC.PAGE_PLUGIN_ID = PP.PAGE_PLUGIN_ID
WHERE P.PAGE_PATH = ?
	AND P.DELETE_FLAG = 0
	AND PC.DELETE_FLAG = 0
	AND PP.DELETE_FLAG = 0
GROUP BY
	P.PAGE_TITLE
