SELECT 
	I.ITEM_ID,
	I.ITEM_NAME,
	I.IMAGE_URL,
	I.DESCRIPTION
FROM Lab_31.ITEM I
	JOIN Lab_31.ITEM_FOR_SALE IFS ON I.ITEM_ID = IFS.ITEM_ID
WHERE IFS.ACTIVE_FLAG = 1
	AND IFS.DELETE_FLAG = 0
	AND I.ACTIVE_FLAG = 1
	AND I.DELETE_FLAG = 0
	AND (CAST(GETDATE() AS DATE) BETWEEN IFS.START_DATE AND IFS.END_DATE)
ORDER BY
	I.ITEM_ID
